export default function elements(document) {
    const DOM = {
        html: document.querySelector("html"),
        windows: document.querySelector(".window"),
        itemForm: document.getElementById("item-form"),
        itemsList: document.querySelectorAll(".items-list"),
        todoList: document.querySelector(".todo-list"),
        noteList: document.querySelector(".note-list"),
        item: document.querySelectorAll(".item"),
        todos: document.getElementsByClassName("todo"),
        notes: document.getElementsByClassName("note"),
        toggleForm: document.querySelector(".toggle-form-type"),
        toggleList: document.querySelector(".toggle-item-list"),
        todoBlock: document.querySelector(".todo-block"),
        noteBlock: document.querySelector(".note-block"),
        navPanel: document.querySelector(".nav-panel"),
        cancelBtn: document.querySelector(".cancel-btn"),
        addItemBtn: document.querySelector(".add-item-btn"),
        menuBtn: document.querySelector(".menu-btn"),
        createItemBtn: document.querySelector(".create-btn"),
        deleteItemBtn: document.querySelector(".delete-btn"),
        changeItemBtn: document.querySelector(".change-btn"),
        checkBtn: document.querySelectorAll(".check-btn"),
        showStorageBtn: document.getElementById("show-local-storage"),
        cleanStorageBtn: document.getElementById("clean-local-storage"),
        callServiceBtn: document.getElementById("call-service-message"),
        serviceMessages: document.querySelector(".service-messages"),
        listTypeInput: document.querySelectorAll("input[name=\"list-type\"]"),
        todoFiltersWrap: document.querySelector(".todo-filters"),
        noteFiltersWrap: document.querySelector(".note-filters"),
        todoFilters: document.querySelectorAll(".todo-filter"),
        todoFilterNormal: document.querySelector(".todo-filter.normal"),
        todoFilterWarning: document.querySelector(".todo-filter.warning"),
        todoFilterUrgent: document.querySelector(".todo-filter.urgent"),
        cancelTodoFilters: document.querySelector(".cancel-todo-filters"),
    };
    return DOM;
} 